services:
  - type: web
    name: eloteria-site
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: NODE_ENV
        value: development
